#!/bin/bash

# Quick setup script for Contact Card on Ubuntu

echo "🚀 Setting up Contact Card for Ubuntu..."

# Install required dependencies
echo "📦 Installing dependencies..."
sudo apt update
sudo apt install -y qrencode xclip xdg-utils

# Create the main contact script
cat > contact_card.sh << 'EOF'
#!/bin/bash
# Contact Card Script - Generated by setup script

NAME="Ujwal Makhija"
TITLE="CEO & FOUNDER" 
PHONE="+919227728888"
EMAIL="ujwal@phonon.io"
WEBSITE="https://www.phonon.io"

# Quick actions
echo "=== Quick Contact Actions ==="
echo "1. Call:    tel:$PHONE"
echo "2. Message: sms:$PHONE" 
echo "3. Email:   mailto:$EMAIL"
echo "4. Website: $WEBSITE"
echo
echo "To use: xdg-open 'tel:$PHONE'"
echo "        xdg-open 'sms:$PHONE'"
echo "        xdg-open 'mailto:$EMAIL'"
echo "        xdg-open '$WEBSITE'"
EOF

# Make executable
chmod +x contact_card.sh

echo "✅ Setup complete!"
echo "🎯 Run './contact_card.sh' to use the contact card"
echo "📞 Quick commands:"
echo "   xdg-open 'tel:+919227728888'"
echo "   xdg-open 'mailto:ujwal@phonon.io'"